name = "cat-manager"
compatibility_date = "2024-09-25"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "cat-manager-db"
database_id = "42c2d83f-0cd7-457e-bfa7-c881ffe57b61"

[[r2_buckets]]
binding = "R2"
bucket_name = "cat-manager-r2"

[[kv_namespaces]]
binding = "KV"
id = "f6452e1053804bf196d8a43828ef3739"

[vars]
JWT_SECRET = "cat-manager-secret-key-2024"
